//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Students
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronimyc { get; set; }
        public string Email { get; set; }
        public System.DateTime EnrollmentDate { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual Final_Departments Final_Departments { get; set; }
    }
}
