//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Departments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Final_Departments()
        {
            this.Final_Courses = new HashSet<Final_Courses>();
            this.Final_Professors1 = new HashSet<Final_Professors>();
            this.Final_Students = new HashSet<Final_Students>();
        }
    
        public int ID { get; set; }
        public string DepartmentName { get; set; }
        public int HeadOfDepartment { get; set; }
        public string PlaceOfDepartment { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Final_Courses> Final_Courses { get; set; }
        public virtual Final_Professors Final_Professors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Final_Professors> Final_Professors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Final_Students> Final_Students { get; set; }
    }
}
