//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Final_Courses()
        {
            this.Final_Schedule = new HashSet<Final_Schedule>();
        }
    
        public int ID { get; set; }
        public string CourseName { get; set; }
        public int MaxHours { get; set; }
        public int DepartmentID { get; set; }
        public int ProfessorID { get; set; }
    
        public virtual Final_Departments Final_Departments { get; set; }
        public virtual Final_Professors Final_Professors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Final_Schedule> Final_Schedule { get; set; }
    }
}
