//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user88_dbEntities2 : DbContext
    {
        public user88_dbEntities2()
            : base("name=user88_dbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Final_Courses> Final_Courses { get; set; }
        public virtual DbSet<Final_Departments> Final_Departments { get; set; }
        public virtual DbSet<Final_Professors> Final_Professors { get; set; }
        public virtual DbSet<Final_Schedule> Final_Schedule { get; set; }
        public virtual DbSet<Final_Students> Final_Students { get; set; }
    }
}
